plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/suhaskiran/appmeasurely-flutter-sdk/frontend"
publishOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "https://uqvknwgcpptxnbmsubkc.supabase.co/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]